### ISSUE TITLE
Version 1.6.0 not working

### ISSUE THREAD

**Issue by renanrfranca** [uberhalit/SekiroFpsUnlockAndMore#48]
You might already be aware, but the FPS hack for version 1.6.0 isn't working on Full Screen. It apparently works with borderless window, but I lose HDR, which is a bummer :/

**Comment by TheBlackRay** [comment]
I don't think the original uploader is active here anymore sadly, I did just try and make some adjustments based on code i found here but to no avail.. I'm very novice when it comes to code and alteration but i gave it my best shot anyways and I got it to recognize 1.6.0! and even got past the unsupported .NET 4.5 framework problem i ran into while in VS, but the game still does not react in anyway to the FPS setting being enabled. I'm assuming but it's very likely the problem is the numbers/values for FPS were adjusted between 1.5 and 1.6 which the code i copied didn't take into account and I'm not even sure what values to look for and change accordingly..  :/  I will try windowed mode and see if it works since my monitor does not support HDR anyways. (EDIT: it works when in borderless window mode but not fullscreen which is very odd.)

**Comment by renanrfranca** [comment]
@TheBlackRay yeah, I'm sure it's not an easy change, and I'm not exactly holding my breath for a fix, but I wanted to open the issue to raise awareness to it, and the fact that it works in borderless might be useful information to someone out there.

It's pretty sad that 1.6.0, which will probably be the final version of Sekiro, does not have a proper FPS fix.

**Comment by technaustin** [comment]
> You might already be aware, but the FPS hack for version 1.6.0 isn't working on Full Screen. It apparently works with borderless window, but I lose HDR, which is a bummer :/

Did you follow the guide and disable Vsync? Works for me on 1.6.0

**Comment by renanrfranca** [comment]
> Did you follow the guide and disable Vsync? Works for me on 1.6.0

Yes. I'll give it another try, but are you positive you are in exclusive full screen and the framerate is being correctly measured above 60? Do you have HDR on? I might try disabling that and see what happens.

**Comment by technaustin** [comment]
Positive. Windowed full screen doesn’t apply HDR properly and looks not
quite as crisp. I had to force VSYNC off. Before I did that I couldn’t
figure out why it was capped, looked up the GitHub and followed the guide
which fixed my issue. My LG TV seems to have a different issue (FPS and HDR
are fine in exclusive, but there is a small bit of tearing. I need to test
again after reboot could have been my system.) My 144hz 4k Samsung works
fine with exclusive fs and HDR, buttery smooth capped at 139fps to avoid
tearing. Borderless full screen works fine too, but the HDR doesn’t apply
properly… everything from the tweak seems to work for me including the
cheats. I don’t think there is a version issue I’m on 1.6.0 as well.

**Comment by renanrfranca** [comment]
> Positive. 

I went through the process again, and this time started off without G-Sync. It worked. I activated G-Sync and it worked as well. I suppose I did something wrong at some point. Thank you very much, I'll close the issue.

Weirdly enough, I'm getting some hiccups, but that's a different investigation. 

Edit: If anyone stumbles upon this in the future, while it worked after following the process without V-Sync and then it worked after activating it and making the necessary changes to the NV control panel, it stopped working after the first launch. Ended up finishing the game at 60 anyway because I couldn't be bothered, but hopefully this helps someone out there.
